# Generated by Django 3.2.5 on 2022-03-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='equipment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('eq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment_type')),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=200)),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment_model')),
            ],
            options={
                'unique_together': {('equipment_model', 'sn')},
            },
        ),
    ]
