# Generated by Django 3.2.5 on 2022-03-31 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_type',
            name='eq_type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='equipment_model',
            unique_together={('brand', 'model')},
        ),
        migrations.CreateModel(
            name='Site_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('eq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment_type')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.site')),
            ],
        ),
    ]
