# Generated by Django 3.2.5 on 2022-03-31 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220331_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_equipment',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_date', models.DateTimeField()),
                ('remove_date', models.DateTimeField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment')),
                ('site_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.site_equipment')),
            ],
        ),
    ]
