# Generated by Django 3.2.5 on 2022-03-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220331_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='remove_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
