# Generated by Django 3.2.5 on 2022-04-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_equpiment_test_shop_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='deploy_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='remove_date',
            new_name='check_out',
        ),
    ]
