# Generated by Django 3.2.5 on 2022-04-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20220404_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_log',
            old_name='checked_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='shop_log',
            old_name='checked_out',
            new_name='check_out',
        ),
    ]
